"""add credit column to case financials

Revision ID: 02b39debca2c
Revises: c9e4b70b668f
Create Date: 2026-08-17 16:41:17.674580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b39debca2c'
down_revision: Union[str, Sequence[str], None] = 'c9e4b70b668f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_financials', sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_financials', 'credit')
    # ### end Alembic commands ###
