"""create membership plan benefits

Revision ID: 0dd13e9d5f82
Revises: bf73bd98a11a
Create Date: 2026-09-16 00:55:54.057944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd13e9d5f82'
down_revision: Union[str, Sequence[str], None] = 'bf73bd98a11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plan_benefits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefit_type', sa.String(length=30), nullable=False),
    sa.Column('monetary_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_limit', sa.Integer(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plan_benefits_business_id'), 'membership_plan_benefits', ['business_id'], unique=False)
    op.create_index(op.f('ix_membership_plan_benefits_plan_id'), 'membership_plan_benefits', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_plan_benefits_plan_id'), table_name='membership_plan_benefits')
    op.drop_index(op.f('ix_membership_plan_benefits_business_id'), table_name='membership_plan_benefits')
    op.drop_table('membership_plan_benefits')
    # ### end Alembic commands ###
