"""create funeral cases table

Revision ID: 3c3910c369fe
Revises: 2b49ed36c623
Create Date: 2026-08-17 11:39:38.928767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3910c369fe'
down_revision: Union[str, Sequence[str], None] = '2b49ed36c623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funeral_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('deceased_full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=200), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=30), nullable=True),
    sa.Column('funeral_date', sa.Date(), nullable=True),
    sa.Column('funeral_venue', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funeral_cases_business_id'), 'funeral_cases', ['business_id'], unique=False)
    op.create_index(op.f('ix_funeral_cases_case_number'), 'funeral_cases', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funeral_cases_case_number'), table_name='funeral_cases')
    op.drop_index(op.f('ix_funeral_cases_business_id'), table_name='funeral_cases')
    op.drop_table('funeral_cases')
    # ### end Alembic commands ###
