"""create case payments table

Revision ID: 7052ea87ce0a
Revises: 02b39debca2c
Create Date: 2026-08-20 13:51:05.103044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7052ea87ce0a'
down_revision: Union[str, Sequence[str], None] = '02b39debca2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['funeral_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_payments_business_id'), 'case_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_case_payments_case_id'), 'case_payments', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_payments_case_id'), table_name='case_payments')
    op.drop_index(op.f('ix_case_payments_business_id'), table_name='case_payments')
    op.drop_table('case_payments')
    # ### end Alembic commands ###
