"""create covered dependents table

Revision ID: 848aa674b699
Revises: d3ede96c0220
Create Date: 2026-09-15 22:48:30.903587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848aa674b699'
down_revision: Union[str, Sequence[str], None] = 'd3ede96c0220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covered_dependents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cover_start_date', sa.Date(), nullable=False),
    sa.Column('cover_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'first_name', 'last_name', 'date_of_birth', name='uq_covered_dependents_membership_person')
    )
    op.create_index(op.f('ix_covered_dependents_business_id'), 'covered_dependents', ['business_id'], unique=False)
    op.create_index(op.f('ix_covered_dependents_membership_id'), 'covered_dependents', ['membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_covered_dependents_membership_id'), table_name='covered_dependents')
    op.drop_index(op.f('ix_covered_dependents_business_id'), table_name='covered_dependents')
    op.drop_table('covered_dependents')
    # ### end Alembic commands ###
