"""create case contacts table

Revision ID: b5a1f9bc70b4
Revises: 6df688e3cb3d
Create Date: 2026-08-17 13:43:16.162125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a1f9bc70b4'
down_revision: Union[str, Sequence[str], None] = '6df688e3cb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['funeral_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_contacts_business_id'), 'case_contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_case_contacts_case_id'), 'case_contacts', ['case_id'], unique=False)
    op.create_index('ix_case_contacts_case_id_created_at', 'case_contacts', ['case_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_contacts_case_id_created_at', table_name='case_contacts')
    op.drop_index(op.f('ix_case_contacts_case_id'), table_name='case_contacts')
    op.drop_index(op.f('ix_case_contacts_business_id'), table_name='case_contacts')
    op.drop_table('case_contacts')
    # ### end Alembic commands ###
