"""add membership links to funeral cases

Revision ID: bf73bd98a11a
Revises: 848aa674b699
Create Date: 2026-09-16 00:07:05.942719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf73bd98a11a'
down_revision: Union[str, Sequence[str], None] = '848aa674b699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funeral_cases', sa.Column('membership_id', sa.UUID(), nullable=True))
    op.add_column('funeral_cases', sa.Column('covered_dependent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_funeral_cases_covered_dependent_id'), 'funeral_cases', ['covered_dependent_id'], unique=False)
    op.create_index(op.f('ix_funeral_cases_membership_id'), 'funeral_cases', ['membership_id'], unique=False)
    op.create_foreign_key(None, 'funeral_cases', 'memberships', ['membership_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'funeral_cases', 'covered_dependents', ['covered_dependent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funeral_cases', type_='foreignkey')
    op.drop_constraint(None, 'funeral_cases', type_='foreignkey')
    op.drop_index(op.f('ix_funeral_cases_membership_id'), table_name='funeral_cases')
    op.drop_index(op.f('ix_funeral_cases_covered_dependent_id'), table_name='funeral_cases')
    op.drop_column('funeral_cases', 'covered_dependent_id')
    op.drop_column('funeral_cases', 'membership_id')
    # ### end Alembic commands ###
