"""add memberships contributions and membership payments

Revision ID: fa5386596a18
Revises: f19abaa4f14a
Create Date: 2026-09-09 21:10:41.292377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5386596a18'
down_revision: Union[str, Sequence[str], None] = 'f19abaa4f14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('membership_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('arrears_since', sa.Date(), nullable=True),
    sa.Column('lapsed_at', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'membership_number', name='uq_memberships_business_membership_number')
    )
    op.create_index(op.f('ix_memberships_business_id'), 'memberships', ['business_id'], unique=False)
    op.create_index(op.f('ix_memberships_member_id'), 'memberships', ['member_id'], unique=False)
    op.create_index(op.f('ix_memberships_plan_id'), 'memberships', ['plan_id'], unique=False)
    op.create_table('membership_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('contribution_period', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'contribution_period', name='uq_membership_contribution_period')
    )
    op.create_index(op.f('ix_membership_contributions_business_id'), 'membership_contributions', ['business_id'], unique=False)
    op.create_index(op.f('ix_membership_contributions_membership_id'), 'membership_contributions', ['membership_id'], unique=False)
    op.create_table('membership_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contribution_id'], ['membership_contributions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'reference', name='uq_membership_payments_business_reference')
    )
    op.create_index(op.f('ix_membership_payments_business_id'), 'membership_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_membership_payments_contribution_id'), 'membership_payments', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_membership_payments_membership_id'), 'membership_payments', ['membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_payments_membership_id'), table_name='membership_payments')
    op.drop_index(op.f('ix_membership_payments_contribution_id'), table_name='membership_payments')
    op.drop_index(op.f('ix_membership_payments_business_id'), table_name='membership_payments')
    op.drop_table('membership_payments')
    op.drop_index(op.f('ix_membership_contributions_membership_id'), table_name='membership_contributions')
    op.drop_index(op.f('ix_membership_contributions_business_id'), table_name='membership_contributions')
    op.drop_table('membership_contributions')
    op.drop_index(op.f('ix_memberships_plan_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_member_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_business_id'), table_name='memberships')
    op.drop_table('memberships')
    # ### end Alembic commands ###
